### ISSUE TITLE
A problem occurred evaluating root project 'web-api-commander'

### ISSUE THREAD

**Issue by pranedon** [RESOStandards/web-api-commander#106]
FAILURE: Build failed with an exception.

* Where:
Build file '/home/gradle/project/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'web-api-commander'.
> Could not find method compile() for arguments [com.google.guava:guava:30.1.1-jre] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by darnjo** [comment]
Hi. Thanks for opening the ticket. Can you provide the environment and arguments you used to produce this error? If you used a configuration file, please send it to dev@reso.org and reference this issue.

**Comment by pranedon** [comment]
Here is the complete log

D:\web-api-commander>docker run --rm -u gradle -v D:/web-api-commander:/home/gradle/project -v D:\web-api-commander\resoscripts:/home/gradle/project/resoscripts -w /home/gradle/project gradle gradle testWebAPICore_2_0_0 -DpathToRESOScript=/home/gradle/project/resoscripts/web-api-server.resoscript -DshowResponses=true --watch-fs --info
Initialized native services in: /home/gradle/.gradle/native
Initialized jansi services in: /home/gradle/.gradle/native

Welcome to Gradle 7.4.1!

Here are the highlights of this release:
 - Aggregated test and JaCoCo reports
 - Marking additional test source directories as tests in IntelliJ
 - Support for Adoptium JDKs in Java toolchains

For more details see https://docs.gradle.org/7.4.1/release-notes.html

Removing 0 daemon stop events from registry
Starting a Gradle Daemon (subsequent builds will be faster)
Starting process 'Gradle build daemon'. Working directory: /home/gradle/.gradle/daemon/7.4.1 Command: /opt/java/openjdk/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /opt/gradle/lib/gradle-launcher-7.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.1
Successfully started process 'Gradle build daemon'
An attempt to start the daemon took 0.963 secs.
The client will now receive all logging from the daemon (pid: 44). The daemon log file: /home/gradle/.gradle/daemon/7.4.1/daemon-44.out.log
Starting build in new daemon [memory: 512 MiB]
Closing daemon's stdin at end of input.
The daemon will no longer process any standard input.
Using 4 worker leases.
Watching the file system is configured to be enabled
Now considering [/home/gradle/project] as hierarchies to watch
File system watching is active
Starting Build
Compiling settings file '/home/gradle/project/settings.gradle' using SubsetScriptTransformer.
Compiling settings file '/home/gradle/project/settings.gradle' using BuildScriptTransformer.
Settings evaluated using settings file '/home/gradle/project/settings.gradle'.
Projects loaded. Root project using build file '/home/gradle/project/build.gradle'.
Included projects: [root project 'web-api-commander']

> Configure project :
Evaluating root project 'web-api-commander' using build file '/home/gradle/project/build.gradle'.
Compiling build file '/home/gradle/project/build.gradle' using SubsetScriptTransformer.
Compiling build file '/home/gradle/project/build.gradle' using BuildScriptTransformer.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/gradle/project/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'web-api-commander'.
> Could not find method classpath() for arguments [com.android.tools.build:gradle:5.2.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s

**Comment by darnjo** [comment]
You'll need to build a container with the GradleDockerfile first. 

One way to do this is to build the container first and then run it:

`docker build --file GradleDockerfile -t web-api-commander-gradle .`

Once the container is built you can use the Gradle commands normally with docker run -it web-api-commander-gradle ...

You can also build the container on the fly:

`docker run --rm -it  -v "$PWD":/home/gradle/project -v /path/to/your/resoscripts:/home/gradle/project/resoscripts -w /home/gradle/project -it $(docker build -f GradleDockerfile -q .) testWebApiCore_2_0_0 -DpathToRESOScript=/home/gradle/project/resoscripts/your.resoscript  -DshowResponses=true`

You'll need to update the paths for Windows. I'll update the documentation next time I make a commit.
