### ISSUE TITLE
Update RESODataDictionary-2.0.xlsx

### ISSUE THREAD

**Issue by Jad212s** [RESOStandards/web-api-commander#119]
The Group attribute has been changed from Utilities to Location for the following fields:

DistanceToBus
DistanceToBusComments
DistanceToBusNumeric
DistanceToSchool Bus
DistanceToSchoolBusComments
DistanceToSchoolBusNumeric
DistanceToSchools
DistanceToSchoolsComments
DistanceToSchoolsNumeric
DistanceToShopping
DistanceToShoppingComments
DistanceToShoppingNumeric
DistanceToStreet
DistanceToStreetComments
DistanceToStreetNumeric
DistanceToFreeway
DistanceToFreewayComments
DistanceToFreewayNumeric
DistanceToPlaceofWorship
DistanceToPlaceofWorshipComments
DistanceToPlaceofWorshipNumeric

The Group attribute was removed for the following field:

PowerProductionOwnership

The RevisedDate has been updated to 2022-06-30 for all of the fields above.

[RESODataDictionary-2.0-2022-06-30.xlsx](https://github.com/RESOStandards/web-api-commander/files/9023102/RESODataDictionary-2.0-2022-06-30.xlsx)

**Comment by bobgott** [comment]
PR #120 has also updated [RESODataDictionary-2.0](https://docs.google.com/spreadsheets/d/1eOB4Nv3wrAayB1av7n2AWPBRWDeB-UkiDa8h8cdsIEI/edit#gid=1651331819) with the proposed xlsx
