### ISSUE TITLE
Minor corrections to RESODataDictionary-1.7-flat.xlsx

### ISSUE THREAD

**Issue by bobgott** [RESOStandards/web-api-commander#124]
_RESODataDictionary-1.7-flat.xlsx_ should be renamed to _RESODataDictionary-1.7-Flattened,xlsx_ to match the source google sheet name [RESODataDictionary-1.7-Flattened](https://docs.google.com/spreadsheets/d/1_59Iqr7AQ51rEFa7p0ND-YhJjEru8gY-D_HM1yy5c6w/edit#gid=544946974).

Also, the last tab, Version Info needs to be updated.

**Comment by darnjo** [comment]
Can this be closed?

**Comment by bobgott** [comment]
Yes, please close
