### ISSUE TITLE
Update to RESODataDictionary-2.0.xlsx

### ISSUE THREAD

**Issue by Jad212s** [RESOStandards/web-api-commander#133]
French-Canadian Translations added to Property Resource Fields

Fields added to InternetTracking Resource:
EventSource
TotalListingViews
TotalListingsFavorited
TotalListingsShared
TotalListingsEmailed
TotalCmaReportsCreated
TotalCmaReportsRan
TotalCmaReportsShared
TotalCmaReportsEmailed
TotalShowingsRequested
TotalShowingsCompleted
TotalLogins
UniqueLogins
MobileLogins

MemberStateLicence Resource added and Fields added:
MemberMlsId
MemberKey
MemberStateLicense
MemberStateLicenseExpirationDate
MemberStateLicenseType
MemberStateLicenseState
ModificationTimestamp
MemberStateLicenseKey

OfficeCorporate Licenses Resource and Fields added:
OfficeMlsId
OfficeKey
OfficeCorporateLicense
OfficeCorporateLicenseState
OfficeCorporateLicenseExpirationDate
OfficeCorporateLicenseType
ModificationTimestamp
OfficeCorporateLicenseKey

EventSource Lookups added:
Map
List
Voice Assistant

MemberType Lookup added:
Photographer

OfficeCorporateLicenseType Lookups added:
Broker
Appraiser 

MemberStateLicenseType Lookups added:
Salesperson
Broker
Appraiser

Smart Appliance(s) Lookup moved to Appliances Field

[RESODataDictionary-2.0-2022-09-08.xlsx](https://github.com/RESOStandards/web-api-commander/files/9530941/RESODataDictionary-2.0-2022-09-08.xlsx)

**Comment by darnjo** [comment]
@Jad212s - I think this can be closed?

**Comment by bobgott** [comment]
I'm done with my work on this issue.

**Comment by Jad212s** [comment]
@darnjo This can be closed.
