### ISSUE TITLE
DataDictionary test fails after pulling Lookup resource

### ISSUE THREAD

**Issue by cobogeri** [RESOStandards/web-api-commander#138]
I had a VM that was running the (new) Data Dictionary tests and was successfully surfacing issues we had with metadata VS lookup. This was running prior to a git pull request early morning 10/3 - now all VM copies error out right after the Lookup resource pull.

[dd17.error.txt](https://github.com/RESOStandards/web-api-commander/files/9709472/dd17.error.txt)

Java -version

openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode, sharing)

Kind regards,
Dave Bills

**Comment by darnjo** [comment]
Hi David. Thanks for reporting this. 

I've been working on an issue to add additional logging for the Lookup Resource, and not fast fail. Can you try this branch and see what happens? https://github.com/RESOStandards/web-api-commander/tree/137-add-additional-logging-for-lookup-resource-tests

**Comment by cobogeri** [comment]
Josh, that did the trick as the test runs to completion.

**Comment by darnjo** [comment]
Glad to hear. I'll get it merged shortly.
