### ISSUE TITLE
Parameter case sensitivity @REQ-WA103-QO1.1

### ISSUE THREAD

**Issue by dgmyrek** [RESOStandards/web-api-commander#14]
This question may need to be routed through the workgroup instead, but I'm starting here. This test is looking specifically for a 400 error when a parameter value like "$SeLeCt" is used, however, our server simply ignores the parameter and doesn't process it as a proper $select as opposed to throwing a 400. We believe this is just as valid of a solution and still adheres to case sensitivity. An equivalent scenario is throwing a garbage parameter name such as "$testing" at a server which, as far as we understand, is within the spec to outright ignore as well. 

@REQ-WA103-QO1.1 @core @2.4.4 @core-endorsement @OData-4.0
Scenario: REQ-WA103-QO1.1 - Query Support: $select case-sensitivity for OData 4.0              # src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:91
Using RESOScript: generic.gold.resoscript
  Given a RESOScript file was provided                                                         # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:73)
RESOScript loaded successfully!
  And Client Settings and Parameters were read from the file                                   # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:80)
Bearer token loaded... first 4 characters: <redacted>
Service root is: https://api.flexmls.com/Reso/OData
  And a test container was successfully created from the given RESOScript                      # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:88)
Authentication Type: authorization_code
  And the test container uses an authorization_code or client_credentials for authentication   # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:95)
Request ID: REQ-WA103-QO1.1
Request URI: https://api.flexmls.com/Reso/OData/Property?$top=5&$SeLeCt=ListingKey,BedroomsTotal&$filter=BedroomsTotal%20eq%209
Request succeeded...91370 bytes received.
  When a GET request is made to the resolved Url in "REQ-WA103-QO1.1"                          # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:311)
Reported OData-Version header value: '4.0'
  And the server has an OData-Version header value of "4.0" or "4.01"                          # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:1019)
Asserted OData Version: 4.0, Server Version: 4.0
Asserted Response Code: 400, Response code: 200
  Then the server responds with a status code of 400 if the server reports OData-Version "4.0" # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:370)
      java.lang.AssertionError: ERROR: asserted response code (400) does not match the one returned from the server (200) !
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.reso.certification.stepdefs.WebAPIServer_1_0_2.lambda$new$17(WebAPIServer_1_0_2.java:379)
        at ?.the server responds with a status code of 400 if the server reports OData-Version "4.0"(file:web-api-commander-master/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:94)

**Comment by darnjo** [comment]
Going by the [OData 4.0 errata 03 ABNF](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/abnf/odata-abnf-construction-rules.txt), `$select`, `$count`, `$orderby`, `$expand`, `$top`, `$filter`, `$metadata` are all _case-sensitive_ because they are singly-quoted in the ABNF:

```
;   This grammar uses the ABNF defined in RFC5234 with one extension: literals 
;   enclosed in single quotes (e.g. '$metadata') are treated case-sensitive. 
;
```

Note that this has been [fixed in the OData 4.01 ABNF](http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt), which is why the tests currently behave as they do. If you are using OData 4.0 and try using `$SeLeCt` when the intent is `$select` then that would fail the test. But if you're using OData 4.01 and use `$SeLeCt` the test will pass.

**Comment by codygustafson** [comment]
I would like to see this issue reopened for workgroup discussion. The grammar doesn't catch sensitive names in 4.0, so they should be ignored just the same as `$testing` is not in the grammar and should be ignored as @dgmyrek notes in the issue description.

**Comment by dgmyrek** [comment]
Reopening for further discussion per Cody's comment

**Comment by darnjo** [comment]
We can discuss this further on the next Cert Subgroup meeting, but I believe the reason the negative test is there for things like `$SeLeCt` is that if someone was implementing the OData 4.0 specification, and they didn't treat the query parameter as case-sensitive and interpreted `$SeLecT` as `$select`, that would be considered an error (HTTP 400) and shouldn't return results (HTTP 200). 

This is not the case for OData 4.01, however. `$SeLeCt` === `$select` in that case, and either should produce results (HTTP 200). 

This would not be the case for the example you gave with the arbitrary parameter of `$testing`, as it's not a valid part of the OData query options, and would always produce an error (HTTP 400).

**Comment by gr33neggs** [comment]
If the intent is to test for core functionality across all implementations, and 4.01 is not a requirement, then the negative test shouldn't be used. The test should just check if the lowercase parameter works and move on since that it the universally supported casing.

**Comment by darnjo** [comment]
These tests have been removed from the Core testing requirements. Closing this issue.
