### ISSUE TITLE
Unexpected change in behaviour

### ISSUE THREAD

**Issue by cobogeri** [RESOStandards/web-api-commander#141]
Not a breaking change.

I noticed that commit [abc27aa](https://github.com/RESOStandards/web-api-commander/commit/abc27aa9dfbe3dfbb5a5348398c4a2662b6b3368) re-introduced the concept of deleting and rebuilding the output directories. Build.Gradle:prepareCertificationEnvironment()

This means if there was a report, say DD, if you run another test (like Core), the old report goes away.

**Comment by darnjo** [comment]
That's correct - there are artifacts produced in the build directory that are dependent on the state of a given run and type of test being run. Therefore each new test needs its own clean environment.  

If you want to run one and then another, I'd suggest either manually copying the results when the job is done or use a scripting language run the tests and copy results out between each run. 

We have a CLI util that will run multiple Data Dictionary tests and copy their results, for instance, but doesn't do both Web API and DD testing. More information here: https://github.com/RESOStandards/reso-certification-utils#batch-test-runner

**Comment by cobogeri** [comment]
That makes sense, thanks. I'll just copy them.
