### ISSUE TITLE
Tests don't run on m1

### ISSUE THREAD

**Issue by letto4135** [RESOStandards/web-api-commander#144]
Recently switched to an m1 Mac from an intel Mac and the tests no longer run as expected.

Using the command
```
./gradlew testWebApiCore_2_0_0 -DpathToRESOScript=../resoscript/web-api-server.core.2.0.0.resoscript  --continue
```
I end up with

```
> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar
> Task :prepareCertificationEnvironment

> Task :testWebApiCore_2_0_0

0 Scenarios
0 Steps
0m0.133s



BUILD SUCCESSFUL in 6s
5 actionable tasks: 5 executed
```
I've tried several versions of java including
```
8.0.345-librca 
11.0.17-zulu
8.0.352.fx-zulu
```

**Comment by darnjo** [comment]
Thanks for reporting this. You can use Docker for now, as there is no ETA for a fix at this time: https://github.com/RESOStandards/web-api-commander/blob/main/doc/Docker.md#reso-automated-testing-tools

**Comment by letto4135** [comment]
This seems to result in the same output... :/

**Comment by letto4135** [comment]
Also a side note, if this is a known issue as I assume it is as fast as you initially responded, why not mention it in the documentation?

**Comment by darnjo** [comment]
You can try using Rosetta 2.
Apple silicon not supported at the current time.

**Comment by darnjo** [comment]
FYI you can try running the Cucumber tests without Gradle. See this Wiki for more info (it was written a while ago but should still work): https://github.com/RESOStandards/web-api-commander/wiki/Automated-Data-Dictionary-Testing-Using-the-RESO-Commander-and-IntelliJ

I'll work on Mac support as I'm using an M2 alongside my Linux machine. I'm just not sure of the timeframe at this point. Need to upgrade Gradle, which is non-trival.

Should work with Rosetta 2 and Intel JVMs though. https://github.com/gradle/gradle/issues/15509

You're the first person to report it.

**Comment by letto4135** [comment]
@darnjo thanks much, the IntelliJ method worked like a charm, with the exception that the instructions point to `/web-api-commander/src/test/java/org/reso/commander/test/features` in the `Enter the following values:` section below the picture, which uses fake data, but the actual tests you want when running your own is what is shown in the picture.

I did fiddle with docker using --platform, but that didn't work either whether that was my fault or not, idk, could have been though, docker is my nemesis.

**Comment by darnjo** [comment]
Thanks, @letto4135. I'm working on the M* version now and will follow up when things are working on that platform. I'll also update the instructions for IntelliJ.
