### ISSUE TITLE
Error when building GradleDockerfile

### ISSUE THREAD

**Issue by cinorthstarmls** [RESOStandards/web-api-commander#157]
I'm encountering an error when trying to build the GradleDockerfile (On MacOS). Any help would be greatly appreciated. 
**Command:**
```docker build --file GradleDockerfile -t web-api-commander-gradle .```

**Error:**
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000002b1c0, pid=43, tid=47
#
# JRE version: OpenJDK Runtime Environment (17.0.7+7) (build 17.0.7+7-alpine-r0)
# Java VM: OpenJDK 64-Bit Server VM (17.0.7+7-alpine-r0, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# C  [libnative-platform-file-events.so+0x2eb8c]  _init+0x39e4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/.gradle/daemon/7.6.1/hs_err_pid43.log
#
# If you would like to submit a bug report, please visit:
#   https://gitlab.alpinelinux.org/alpine/aports/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by darnjo** [comment]
Hi there. Thanks for reporting this. 

What kind of Mac are you on? I was able to build the container successfully on an Air M2. 

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/535358/236891907-3aa4d902-3fac-4fe0-9e3a-31c4b485f30a.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/535358/236891965-1960629b-52b6-4c53-891c-25ecce752255.png">


We have pre-built containers if that helps.

**Comment by cinorthstarmls** [comment]
I'm also using a Mac M2. Since this is my first build, it's completely fresh. Is it possible that your docker build cache is being used instead of totally rebuilding the image?

Is the pre-built image stored in a public registry? How can I access it?

**Comment by darnjo** [comment]
I'll look into the local build.

You can find the [ECR image here](https://gallery.ecr.aws/reso-commander/reso-commander-docker).
