### ISSUE TITLE
Data Dictionary 2.0 File

### ISSUE THREAD

**Issue by Jad212s** [RESOStandards/web-api-commander#168]
[RESODataDictionary-2.0.xlsx](https://github.com/RESOStandards/web-api-commander/files/12834841/RESODataDictionary-2.0.xlsx)

The original ticket addressed the updates to change CaravanStops, MemberStateLicenses, and OfficeCorporateLicenses to their singular version: CaravanStop, MemberStateLicense, and OfficeCorporateLicense, as well as resolving some duplicate lookup names.

**Comment by Jad212s** [comment]
Updated SugMaxPrecision for:

AboveGradeFinishedArea
BelowGradeFinishedArea
Listing Latitude
Listing Longitude
TaxAnnualAmountPerLivingAreaUnit

**Comment by Jad212s** [comment]
Field Changes

<html>
<body>
<google-sheets-html-origin>

Type | Resource | Field | Column | Previous Value | New Value
-- | -- | -- | -- | -- | --
Change | Caravan | CaravanOrganizerResourceName | SimpleDataType | Number | String List, Single
Change | Caravan | CaravanOrganizerResourceName | LookupName |   | CaravanResourceName
Change | Caravan | CaravanOrganizerResourceName | SimpleDataType |   | String List, Single
Change | Caravan | CaravanOrganizerResourceName | LookupStatus |   | Open with Enumerations
Change | CaravanStop | StopAttendedBy | LookupName | Attended | CaravanStopAttended
Change | CaravanStop | StopResourceName | LookupName | CaravanStopsResourceNames | CaravanResourceName
Change | LockOrBox | ListingLatitude | SugMaxPrecision |   | 8
Change | LockOrBox | ListingLongitude | SugMaxPrecision |   | 8
Change | MemberStateLicense | MemberStateLicenseState | LookupStatus |   | Open with Enumerations
Change | MemberStateLicense | MemberStateLicenseType | LookupStatus |   | Open with Enumerations
Change | OfficeCorporateLicense | OfficeCorporateLicenseState | LookupStatus |   | Open with Enumerations
Change | OfficeCorporateLicense | OfficeCorporateLicenseType | LookupStatus |   | Open with Enumerations
Change | PowerStorage | NameplateCapacity | SugMaxPrecision |   | 2
Change | PowerStorage | PowerStorageType | LookupStatus |   | Open with Enumerations
Change | Property | AboveGradeUnfinishedArea | SugMaxPrecision |   | 2
Change | Property | BelowGradeUnfinishedArea | SugMaxPrecision |   | 2
Change | Property | PropertyTimeZoneStandardOffset | SimpleDataType | String | Number
Change | Property | TaxAnnualAmountPerLivingAreaUnit | SugMaxPrecision |   | 2


</body>
</html>

**Comment by darnjo** [comment]
Thanks for putting this table together, Jason.

@sdebord, I think these changes are ready to review and approve. Note that I haven't build/tested them yet so we could find other things as well.

**Comment by Jad212s** [comment]
Attached is the 2.0 sheet with all of the definition updates. Does not include items approved after ratification.

[RESODataDictionary-2.0 2023-11-01.xlsx](https://github.com/RESOStandards/web-api-commander/files/13232984/RESODataDictionary-2.0.2023-11-01.xlsx)

**Comment by darnjo** [comment]
Thanks, Jason.
