### ISSUE TITLE
2024-01-17 DD Sheet Update

### ISSUE THREAD

**Issue by Jad212s** [RESOStandards/web-api-commander#185]
[2024-01-17-RESODataDictionary-2.0.xlsx](https://github.com/RESOStandards/web-api-commander/files/13967427/2024-01-17-RESODataDictionary-2.0.xlsx)

The following corrections were made on the attached sheet:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jdarr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jdarr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Sheet | Resource | Field | Lookup | Column | Old   Value | New   Value
-- | -- | -- | -- | -- | -- | --
Fields | Property | SourceSystem | - | SimpleDataType | Collection | Resource
Fields | Media | OriginatingSystemResourceRecordId | - | SugMaxLength | 25 | 255
Fields | Media | SourceSystemResourceRecordId | - | SugMaxLength | 25 | 255
Lookups | - | ListingTerms | Owner   Will Carry | Definition | The   seller will carry points | The   seller will carry the mortgage note.

</body>

</html>

**Comment by darnjo** [comment]
Is this still something that needs to be addressed?

**Comment by Jad212s** [comment]
It has been addresses. Closing the ticket.
