### ISSUE TITLE
DD 2.0 Lookup Ids missing

### ISSUE THREAD

**Issue by tlingard** [RESOStandards/web-api-commander#197]
Are the `LookupNameId` & `LookupId` columns in the DD Lookup sheet still used? They are still listed in the [Data Dictionary Terms and Meta Definitions](https://ddwiki.reso.org/display/DDW20/Data+Dictionary+Terms+and+Meta+Definitions) as unique identifiers.

Both are missing for all `ArchitecturalStyle` lookup values and the single `CommunityFeatures(Pickleball)` value

**Comment by darnjo** [comment]
Hi. Thanks for opening a ticket. 

This is more of a support question than something related to the Commander. For non-Commander issues, please reach out to dev at reso.

We still use LookupId and all the other ID fields. 

If you look at [A-Frame](https://ddwiki.reso.org/display/DDW20/A-Frame), you can see both LookupID and LookupNameID are present.

<img width="253" alt="image" src="https://github.com/RESOStandards/web-api-commander/assets/535358/d242e180-8558-4e89-821b-3bd19817d82e">

Similar with [Pickleball](https://ddwiki.reso.org/display/DDW20/Pickleball):

<img width="221" alt="image" src="https://github.com/RESOStandards/web-api-commander/assets/535358/ab85f475-a2a3-4f07-b901-e45d7ac65eeb">

We have, however, deprecated the old IDs in favor of hashes. The old IDs are now in the LegacyLookupNameId and LegacyLookupId columns in the DD reference sheets.

**Comment by darnjo** [comment]
Nice to hear you're using the reference sheets for schema generation. We do similar for Certification. We have some reference JSON Schema if that's helpful (though it sounds like you're using more than what might be there). 

In that case, feel free to open tickets on this repo when you see anything awry. The feedback/QA is much appreciated and helps us address potential issues.

I'm guessing you got an intermediate update before the DD Wiki had been regenerated, as the lookup names and IDs come from that process. Working on adding it to the build process so it happens automatically but need to do a little work there first.

We probably need to update the definitions a bit in the DD Wiki to reflect the current items in the sheet. There are also some schema changes to the reference sheets for DD 2.1 starting this Fall FYI.

**Comment by darnjo** [comment]
As a side note, the [current DD 2.0 reference sheet](https://github.com/RESOStandards/web-api-commander/blob/main/src/main/resources/RESODataDictionary-2.0.xlsx) shouldn't have any blank lookup name IDs or lookup IDs, so I don't think you need to get them from the website.
