### ISSUE TITLE
DD-2.0-Corrections

### ISSUE THREAD

**Issue by Jad212s** [RESOStandards/web-api-commander#201]
This is an updated request to #200 

[RESODataDictionary-2.0-Corrections-2024-08-15.xlsx](https://github.com/user-attachments/files/16630032/RESODataDictionary-2.0-Corrections-2024-08-15.xlsx)

The attached sheet included the following corrections:

**Fields**
[OfficeCountry](https://ddwiki.reso.org/display/DDW20/OfficeMailCountry+Field)

- Change SimpleDataType to String List, Single
- Add LookupName - Country
- Add LookupStatus - Open with Enumerations

[OfficeMailCountry](https://ddwiki.reso.org/display/DDW20/OfficeMailCountry+Field)

- Change SimpleDataType to String List, Single
- Add LookupName - Country
- Add LookupStatus - Open with Enumerations

[OfficeMailStateOrProvince](https://ddwiki.reso.org/display/DDW20/OfficeMailStateOrProvince+Field)

- Change SimpleDataType to String List, Single
- Add LookupName - StateOrProvince
- Add LookupStatus - Open with Enumerations

[OfficeMailCountyOrParish](https://ddwiki.reso.org/display/DDW20/OfficeMailCountyOrParish+Field)

- Change SimpleDataType to String List, Single
- Add LookupName - CountryOrParish
- Add LookupStatus - Open

[AssociationCountyOrParish](https://ddwiki.reso.org/display/DDW20/AssociationCountyOrParish+Field)

- Change LookupStatus to Open

[AssociationMailCountyOrParish](https://ddwiki.reso.org/display/DDW20/AssociationMailCountyOrParish+Field)

- Change LookupStatus to Open

[RuleKey](https://ddwiki.reso.org/display/DDW20/RuleKey+Field)

- Change the definition to, “The primary key of the individual Rule record.”

Change SugMaxLength to 50 for:
- [OfficeMailAddress1](https://ddwiki.reso.org/display/DDW20/OfficeMailAddress1+Field)
- [OfficeMailAddress2](https://ddwiki.reso.org/display/DDW20/OfficeMailAddress2+Field)
- [OfficeMailCity](https://ddwiki.reso.org/display/DDW20/OfficeMailCity+Field)
- [OfficeMailCountyOrParish](https://ddwiki.reso.org/display/DDW20/OfficeMailCountyOrParish+Field)

**Lookups**
[Single Family Residence](https://ddwiki.reso.org/display/DDW20/Single+Family+Residence)
- Revert definition to, "A single family residence on real property."

[Minimal lnterior Lighting](https://ddwiki.reso.org/display/DDW20/Minimal+lnterior+Lighting)
- Replace the lowercase “L” with a capital “I” as the first letter of the word “Interior” on the StandardLookupValue and LegacyODataValue

[Virtual Staging – Item Addition](https://ddwiki.reso.org/display/DDW20/Virtual+Staging+++Item+Addition)
- Replace em dash "–" with en dash "-"

[Virtual Representation – To Be Built](https://ddwiki.reso.org/display/DDW20/Virtual+Representation+++To+Be+Built)
- Replace em dash "–" with en dash "-"

[Virtual Representation – Under Construction](https://ddwiki.reso.org/display/DDW20/Virtual+Representation+++Under+Construction)
- Replace em dash "–" with en dash "-"

[Decluttered – Item Removed](https://ddwiki.reso.org/display/DDW20/Decluttered+++Item+Removed)
- Replace em dash "–" with en dash "-"

[GIS Calculated](https://ddwiki.reso.org/pages/viewpage.action?pageId=1138788)
 - Change LegacyODataValue to GisCalculated

[Gps](https://ddwiki.reso.org/display/DDW20/EventSource+Field)
- Change StandardLookupValue to GPS
- Change LegacyODataValue to Gps

[Hawaii–Aleutian](https://ddwiki.reso.org/display/DDW20/Hawaii+Aleutian)
- Replace em dash "–" with en dash "-"

**Other Corrections**
- FrenchCanadianDisplayName attributes on Lookups.
- Grammar and spelling of field and lookup definitions.

**Comment by darnjo** [comment]
Closing in favor of #202.
