### ISSUE TITLE
Data Dictionary 2.0 Errata - Sept 2024

### ISSUE THREAD

**Issue by darnjo** [RESOStandards/web-api-commander#202]
This ticket covers DD 2.0 errata that were discussed in the September DD meeting.

**Comment by Jad212s** [comment]
[RESODataDictionary-2.0-Corrections-2024-09-19.xlsx](https://github.com/user-attachments/files/17067606/RESODataDictionary-2.0-Corrections-2024-09-19.xlsx)

The attached sheet contains the following corrections to DD 2.0

**Fields**
[AssociationCountyOrParish](https://ddwiki.reso.org/display/DDW20/AssociationCountyOrParish+Field)
 - Change LookupStatus to Open
 
[AssociationMailCountyOrParish](https://ddwiki.reso.org/display/DDW20/AssociationMailCountyOrParish+Field)
 - Change LookupStatus to Open

[RuleKey](https://ddwiki.reso.org/display/DDW20/RuleKey+Field)
- Change the definition to, “The primary key of the individual Rule record.”

**Lookups**
[Single Family Residence](https://ddwiki.reso.org/display/DDW20/Single+Family+Residence)

 - Revert definition to, "A single family residence on real property."

[Minimal lnterior Lighting](https://ddwiki.reso.org/display/DDW20/Minimal+lnterior+Lighting)
- Replace the lowercase “L” with a capital “I” as the first letter of the word “Interior” on the StandardLookupValue and LegacyODataValue

[Virtual Staging – Item Addition](https://ddwiki.reso.org/display/DDW20/Virtual+Staging+++Item+Addition)
 - Replace em-dash "–" with hyphen-minus "-"

[Virtual Representation – To Be Built](https://ddwiki.reso.org/display/DDW20/Virtual+Representation+++To+Be+Built)
 - Replace em-dash "–" with hyphen-minus "-"

[Virtual Representation – Under Construction](https://ddwiki.reso.org/display/DDW20/Virtual+Representation+++Under+Construction)
 - Replace em dash "–" with hyphen-minus "-"
 
[Decluttered – Item Removed](https://ddwiki.reso.org/display/DDW20/Decluttered+++Item+Removed)
- Replace em dash "–" with hyphen-minus "-"

[Hawaii–Aleutian](https://ddwiki.reso.org/display/DDW20/Hawaii+Aleutian) (Used by PropertyTimeZone and ShowingTimeZone fields)
 - Replace em dash "–" with hyphen-minus "-"

[GIS Calculated](https://ddwiki.reso.org/pages/viewpage.action?pageId=1138788)
- Change LegacyODataValue to GisCalculated

[Gps](https://ddwiki.reso.org/display/DDW20/EventSource+Field)
- Change StandardLookupValue to GPS
 - Change LegacyODataValue to Gps

**Other Corrections**
 - FrenchCanadianDisplayName attributes on Lookups.
 - Spelling and punctuation of field and lookup definitions.
