### ISSUE TITLE
REQ-WA103-QO12 failing with NullPointerException

### ISSUE THREAD

**Issue by jerretrobison** [RESOStandards/web-api-commander#23]
`gradlew testWebAPIServer_1_0_2_Platinum  -DshowResponses=true -DpathToRESOScript="..." -Dcucumber.filter.tags="@REQ-WA103-QO12"`

> @REQ-WA103-QO12 @platinum @2.4.4 @filterability-endorsement @filterability-endorsement
> Scenario: REQ-WA103-QO12 - Query Support: $filter - Grouping: filter (ge, le) and (gt, lt) and expect (gt, lt) # src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:687
> Using RESOScript:
> ...
> **And the OData client response has client entity set data                                                     # org.reso.certification.stepdefs.WebAPIServer_1_0_2.<init>(WebAPIServer_1_0_2.java:918)
>       java.lang.NullPointerException
>         at org.reso.certification.stepdefs.WebAPIServer_1_0_2.lambda$new$59(WebAPIServer_1_0_2.java:920)
>         at ?.the OData client response has client entity set data(file:///C:/Users/e5001999/web-api-commander/src/main/java/org/reso/certification/features/web-api/web-api-server-1.0.2.feature:692)**
> ...
> 

The error comes from here:
https://github.com/RESOStandards/web-api-commander/blob/59c409d37d5a2b2cc8686230ee1c6e35072fcf09/src/main/java/org/reso/certification/stepdefs/WebAPIServer_1_0_2.java#L920

Counting the returned entities seems to be the intent of the code. Consider this as a possible fix:
`assertTrue("ERROR: no results returned!", getTestContainer().getClientEntitySet().getEntities().size() > 0);`

**Comment by darnjo** [comment]
Thanks for reporting this, @jerretrobison. I'll take a look!

**Comment by darnjo** [comment]
Referenced test item "REQ-WA103-QO12" is no longer used. 

If this is still an issue with the current codebase, please open another ticket.
