### ISSUE TITLE
DataSystem TimeZoneOffset

### ISSUE THREAD

**Issue by EnFinlay** [RESOStandards/web-api-commander#32]
Error message during testing:

`$.value[0].Resources[3].TimeZoneOffset: string found, integer expected`

The value of `TimeZoneOffset` that's causing the error is "GMT+0".

According to the WebAPI 1.0.2 Spec, this is the correct format: https://members.reso.org/display/API2/2.6.1+DataSystem+Resource

> TimeZoneOffset | The TimeZone Offset provided in standard TimeZone notation of GMT[+\|-]X, where X is the number of hours in the offset.

**Comment by darnjo** [comment]
Thanks for opening this ticket, @EnFinlay.
@jerretrobison had previously asked a similar question, which we'd discussed a bit in the workgroups. 

[In the specification for DataSystem](https://members.reso.org/display/API2/Appendix+4+-+DataSystem+XML+Schema), TimeZoneOffset is currently defined as an Integer, which is reflected in the [JSON Schema being used to validate the payload](https://github.com/RESOStandards/web-api-commander/blob/a2843cad82be809f853f925818aeda9a9d01f4d3/src/main/resources/datasystem.schema.4.json#L80) from this endpoint in the testing rules. I would perhaps prefer to make it a string, and allow only ISO 8601 time zone offsets, but a decimal would be fine too as long as we're clear that +hh.25 means "+hh:15".

**Comment by EnFinlay** [comment]
The wording of the spec makes me think the "GMT" is meant to be included, but you're right the schema is clearly an int. Shouldn't cause any issues for me to change what data we're returning there, but I think it should be clarified in the spec.

**Comment by darnjo** [comment]
I think the testing for this will likely be removed from core, but if
there's interest in having an endorsement for it, we may want to consider
changing the data type so that fractional time zones can be included.
