### ISSUE TITLE
Clean up generic.resoscript input references

### ISSUE THREAD

**Issue by dgmyrek** [RESOStandards/web-api-commander#4]
There is at least one XML entity in the generic resoscript file that makes a reference to a single quoted value, whereas it's actually looking for an unquoted value. 

https://github.com/RESOStandards/web-api-commander/blob/648c26358d760b12c4e4c25f5d3668aaf4846d33/generic.resoscript#L125

Further down we see slightly different notation for what should be the same format :
https://github.com/RESOStandards/web-api-commander/blob/master/generic.resoscript#L174
https://github.com/RESOStandards/web-api-commander/blob/master/generic.resoscript#L179

Super minor overall, but would be good to clean these up and make them uniform.

**Comment by darnjo** [comment]
Should be fixed in the main branch.

**Comment by darnjo** [comment]
I think this should be OK now?
