### ISSUE TITLE
Remove or clean up reference to Parameter_FilterHasField and Parameter_FilterHasValueLookupValue

### ISSUE THREAD

**Issue by dgmyrek** [RESOStandards/web-api-commander#5]
https://github.com/RESOStandards/web-api-commander/blob/648c26358d760b12c4e4c25f5d3668aaf4846d33/generic.resoscript#L258

These parameters have no equivalent "Required Fields and Values" section params so they come through null and cause a handful of tests to fail. 

One test in particular is REQ-WA103-QO8

**Comment by darnjo** [comment]
Good catch. I fixed this in the generic.gold.resoscript but not in the
generic one. I'll push a fix.

**Comment by darnjo** [comment]
Should be fixed in the main branch now.
