### ISSUE TITLE
Parameter_ExpandField included in $select in a number of tests

### ISSUE THREAD

**Issue by dgmyrek** [RESOStandards/web-api-commander#6]
https://github.com/RESOStandards/web-api-commander/blob/cccd671c99d0f37768cae41fcaacfd338e2eb2f5/generic.resoscript#L731

Parameter_ExpandField included in the $select param fails on our server since we're only allowing fields included in the $metadata to be used within that param. Including it in the $expand parameter should be enough to fulfill the obligations of the test, no?

**Comment by darnjo** [comment]
Hi Dylan. Thanks for reporting this. 

I have recently split out the RESOScript templates into a Platinum template, `generic.resoscript`, and a Gold template, `generic.gold.resoscript`. These items use different `$select` lists, but it's useful to have a static select list created ahead of time so I can ensure each field in the select list is  defined in the way we expect it to be in the metadata. [However, for `$expand` queries, the expand field is added to the list separately](https://github.com/RESOStandards/web-api-commander/blob/master/generic.resoscript#L537-L553). 

If it's helpful for the purposes of running in `runRESOScript` mode, I could also remove the Platinum requests from the `generic.gold.resoscript` file. In automated testing mode, the Platinum tests are ignored but if one is trying to run the queries and download the results, the Platinum fields might be missing in the configuration and could lead to 400/500 errors in the responses.

**Comment by darnjo** [comment]
This should be taken care of at this point.
