### ISSUE TITLE
Error in getMetadata

### ISSUE THREAD

**Issue by rich0726** [RESOStandards/web-api-commander#63]
I'm trying to use test-commander to start to validate our RESO API.  When I run the jar to do a "getMetadata", I get an error file generated with the following message:

ERROR: request failed!
URI: https://localhost:5001/odata/$metadata
Exception: org.apache.olingo.client.api.http.HttpClientException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Can you help me figure out why this is?

**Comment by darnjo** [comment]
Hi @rich0726, thanks for the question.

Have you verified that you have set up SSL certs on your local server? You could try making the request with `http` instead...

**Comment by rich0726** [comment]
For now I'm just using a self-signed certificate generated by IIS express.  In Googling this particular error, it seems like I need to export the certificate to a .cer file, then use keytool to import to a JavaKeyStore (jks).  I did all that and I'm still getting the error.  I don't know what to do with the jks once I have it though.

**Comment by rich0726** [comment]
FWIW, if I disable SSL on my localhost, getMetadata works just fine, so it's definitely something to do with Java not seeing the certificate.

**Comment by darnjo** [comment]
Thanks, Rich. We have tested the tool on production servers with HTTPS, which is what we use to do all of our testing, so I'm fairly confident the library and code can handle it, I think it's something about the Apache client library doing additional validation on your SSL config and it's not finding something it's expecting. Perhaps we can chat a bit further or you could provide me with a Docker image of your local environment and/or steps to reproduce (how did you sign the cert, etc)? 

Feel free to send an email to dev@reso.org if you'd like to have a quick meeting about it instead...

**Comment by rich0726** [comment]
I think I can probably work through this once I move off of localhost and use a real certificate.  Thanks for the help.  I'll close the issue for now.
