### ISSUE TITLE
Issue with filter-coll-enum-all.json and filter-coll-enum-any.json

### ISSUE THREAD

**Issue by rich0726** [RESOStandards/web-api-commander#65]
I've got tests failing based on the default queries for filter-coll-enum-all and filter-coll-enum-any.  The filter clause for those queries are defined like this: 
AccessibilityFeatures/all(enum: enum eq org.reso.metadata.enums.AccessibilityFeatures'AccessibleApproachWithRamp')

However, because I need to persist my enums as classes in my EntityModel, the enums are a property of the containing class.  That would mean the filter query would need to be something like:

AccessibilityFeatures/all(enum: enum/MyEnumProperty eq org.reso.metadata.enums.AccessibilityFeatures'AccessibleApproachWithRamp')

where MyEnumProperty is the enum-based property within my AccessibilityFeatures lookup class that contains the lookup value.

Unless I'm missing something, this test doesn't seem to be canonical oData for an "all" query.

Thanks in advance!

**Comment by darnjo** [comment]
In this case, the lookup is defined as a collection of OData Edm.EnumType
objects. Each item in that collection should therefore support the eq
operator on it's fully qualified namespace?

This is similar to the singular case of StandardStatus eq
org.reso.metadata.StandardStatus'Active' except we're applying the eq
operator to each Edm.EnumType in the collection.

IIRC I took this syntax from existing OData examples and it seems to work
on the parsers for the servers we've tested so far but would be happy to
chat further about it.

**Comment by darnjo** [comment]
FYI, it won't make a difference in this case, but you should be using the [following branch](https://github.com/RESOStandards/web-api-commander/tree/add-jenkins-dd-gradle-task) instead since we added support for `$count=true` in the workgroups and then in #55. Let me know if you have any issues. I'm working on some code there but it shouldn't affect the tests, which we also have acceptance tests for, more about reporting.

**Comment by rich0726** [comment]
Josh,
Would love to set up some time to talk through this with you.  I’m spinning my wheels trying to get SQL Server, EntityFrameworkCore, and Microsoft.OData to all play nicely with one another.

Drop me an email at ***@***.******@***.***> with your availability for the next few days, if you have some time.

Thanks!
Rich Gunther
FoliumIS

**Comment by darnjo** [comment]
Looks like GitHub removed email addresses 

I'm free all next Monday, March 29. Email me at josh at reso.org.

**Comment by darnjo** [comment]
Circling back to this. 

> However, because I need to persist my enums as classes in my EntityModel, the enums are a property of the containing class. That would mean the filter query would need to be something like:
> 
> AccessibilityFeatures/all(enum: enum/MyEnumProperty eq org.reso.metadata.enums.AccessibilityFeatures'AccessibleApproachWithRamp')

In this case, the standard is fairly prescriptive about how enumerations should appear in the metadata. As such, the queries should work as currently written.

There are two choices:

1. Use OData Edm.EnumType definitions. 
2. Use the "Lookup Resource" to advertise enumerations, in which case you can use Edm.String or Collection(Edm.String) in the fields that use those enumerated values. 

See the Web API Core 2.0.0 specification for more information. https://github.com/RESOStandards/reso-transport-specifications/blob/main/web-api-core.md#2599-multiple-enumerations
