### ISSUE TITLE
$expand Refinements

### ISSUE THREAD

**Issue by EnFinlay** [RESOStandards/web-api-commander#9]
While working on the `$expand` tests, I had to make some tweaks. This issue captures the reasoning behind the changes that are in the related PR.

1. Line 895 reads like it belongs inside the `if (clientProperty.getName().equals(expandField)) {` statement (https://github.com/RESOStandards/web-api-commander/blob/master/src/main/java/org/reso/certification/stepdefs/WebAPIServer_1_0_2.java#L897). I haven't been able to get the `type` check to pass even with valid Navigation Property metadata. Maybe it should be removed entirely?

2. If the `expand` field's value is null, the test doesn't fail since there is no guarantee that every record will have a valid reference to other records.

**Comment by darnjo** [comment]
Assuming there's still a question about the first item and type, I was expecting the name of the type to be that which was declared in the EDM. IIRC, in this case it was MemberComplexType? 

In inspecting the primitive types, they always had accompanying type information for their values across various servers. I didn't have a lot to go by when a complex type was used, but I can look further into the specification and code and see what the expectation is. It could be that the conditions captured so far aren't sufficient to check for the case accurately when a complex type is used. Perhaps you could send me a sample of the metadata that contains the type info directly and I can verify it and debug further?

**Comment by EnFinlay** [comment]
I don't think the type should be a ComplexType, it should just reference another EntityType in the EDM http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752536. Example in the docs: `<NavigationProperty Name="Supplier" Type="Self.Supplier" />`. I don't know how to check this in the code though - I looked through the docs and couldn't find anyway of getting the type in this situation.

I've added Navigation Properties to our metadata, so you should be able to see them with your access_token. (https://api.bridgedataoutput.com/api/v2/OData/abor_ref/$metadata)

**Comment by darnjo** [comment]
Thanks for adding the navigation properties. That will allow me to debug a
bit, and we should be able to resolve the issue. As an aside, the tests
that are still in progress are tagged with @todo in the gherkin spec, and
the scenario descriptions reflect that too. As we finish these items, I'll
remove the TODOs.

**Comment by EnFinlay** [comment]
If I have time I'll help out where I can.

**Comment by darnjo** [comment]
The tests referenced in this issue will be addressed by Web API Core 2.1.0. See #143.
